[package]
name = "window"
version = "0.1.0"
edition = "2021"

[features]
profile = ["mini/profile"]
info = ["mini/info"]
warn = ["mini/warn"]
error = ["mini/error"]

[dependencies]
crossbeam-queue = "0.3.11"
mini = { git = "https://github.com/zx3no/mini", version = "0.1.0" }
